/**
 * Tool catalog
 * ------------
 * A catalog is the universe of tools Toolgate can choose from. In a real
 * deployment this is generated by connecting to every configured MCP server
 * and reading its advertised `tools/list`. Here we load it from a JSON file so
 * the project runs with zero setup and the demo is deterministic.
 *
 * @typedef {Object} Tool
 * @property {string} name         Unique id, e.g. "confluence.search".
 * @property {string} server       Owning MCP server, e.g. "confluence-jira".
 * @property {string} description  One-line human/agent-facing description.
 * @property {string[]} [keywords] Extra terms to match on.
 * @property {object} [schema]     The tool's JSON input schema (drives cost).
 * @property {number} [latencyMs]  Typical latency; feeds the cost model.
 * @property {number} [risk]       0..1 sensitivity (writes, secrets, PII).
 */

import { readFileSync } from "node:fs";

/**
 * @param {string} path
 * @returns {Tool[]}
 */
export function loadCatalog(path) {
  const raw = JSON.parse(readFileSync(path, "utf8"));
  if (!Array.isArray(raw.tools)) {
    throw new Error(`Catalog at ${path} must have a "tools" array`);
  }
  return raw.tools;
}
